# Generated by Django 3.0 on 2021-01-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.IntegerField(unique=True)),
                ('line_remark', models.CharField(max_length=200)),
                ('line_port', models.IntegerField(default=0)),
                ('line_uuid', models.CharField(default='', max_length=200)),
                ('line_expire_date', models.DateTimeField(blank=True)),
                ('line_enable', models.IntegerField(default=0)),
                ('line_transfer', models.BigIntegerField(default=0)),
                ('line_server_domain', models.CharField(default='', max_length=200)),
                ('line_user_id', models.IntegerField()),
                ('line_device_limit', models.IntegerField(default=0)),
                ('line_device_num', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'line',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('money_total', models.IntegerField(default=0)),
                ('money_left', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'money',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.IntegerField(unique=True)),
                ('server_ip', models.CharField(default='', max_length=200)),
                ('server_domain', models.CharField(default='', max_length=200)),
                ('server_location', models.CharField(default='', max_length=200)),
                ('server_line_num', models.IntegerField(default=0)),
                ('server_line_max', models.IntegerField(default=0)),
                ('server_tag', models.CharField(default='', max_length=200)),
                ('server_load', models.CharField(default='', max_length=200)),
                ('server_speed', models.CharField(default='', max_length=200)),
                ('server_transfer', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'server',
                'managed': True,
            },
        ),
    ]
