# Generated by Django 3.0 on 2021-01-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=200, unique=True)),
                ('user_pass', models.CharField(default='', max_length=200)),
                ('user_email', models.CharField(default='', max_length=200)),
                ('user_contact_type', models.CharField(default='', max_length=200)),
                ('user_contact_num', models.CharField(default='', max_length=200)),
                ('user_reg_date', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
